import fs from "node:fs/promises";
import path from "node:path";
import { env } from "@/lib/env";
import type { AgentRow, BrandRow, TaskRow, TaskStatus } from "@/types/db";

/**
 * Vault write-side. The vault is OneDrive-synced at OBSIDIAN_VAULT_PATH;
 * we only ever write whole files (atomic-ish) and never delete.
 */
export function vaultConfigured(): boolean {
  return Boolean(process.env.OBSIDIAN_VAULT_PATH);
}

async function writeVaultFile(relPath: string, content: string): Promise<string> {
  const full = path.join(env.obsidianVaultPath, relPath);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, content, "utf8");
  return full;
}

async function readVaultFile(relPath: string): Promise<string | null> {
  try {
    return await fs.readFile(path.join(env.obsidianVaultPath, relPath), "utf8");
  } catch {
    return null;
  }
}

/** Write an arbitrary vault document (used for the BrightOS memory digest). */
export async function writeVaultDoc(relPath: string, content: string): Promise<string | null> {
  if (!vaultConfigured()) return null;
  return writeVaultFile(relPath, content);
}

/** Append a section to the daily note (creates the note if needed). */
export async function appendToDailyNote(day: string, sectionMd: string): Promise<string | null> {
  if (!vaultConfigured()) return null;
  const rel = path.join(env.obsidianDailyNotesDir, `${day}.md`);
  const existing = await readVaultFile(rel);
  const content = existing ? `${existing.trimEnd()}\n\n${sectionMd}\n` : `# ${day}\n\n${sectionMd}\n`;
  return writeVaultFile(rel, content);
}

export async function writeCloseout(week: string, md: string): Promise<string | null> {
  if (!vaultConfigured()) return null;
  return writeVaultFile(path.join(env.obsidianCloseoutDir, `${week}.md`), md);
}

const BOARD_COLUMNS: { status: TaskStatus; label: string }[] = [
  { status: "backlog", label: "BACKLOG" },
  { status: "assigned", label: "ASSIGNED" },
  { status: "in_progress", label: "IN PROGRESS" },
  { status: "awaiting_approval", label: "AWAITING APPROVAL" },
  { status: "verified", label: "VERIFIED" },
  { status: "shipped", label: "SHIPPED" },
];

/**
 * "Active Command Board.md" — rendered from the DB so the vault board can
 * never go stale. Regenerated by workers + the watcher on every change.
 */
export function renderCommandBoard(input: {
  tasks: TaskRow[];
  agents: Pick<AgentRow, "id" | "name">[];
  brands: Pick<BrandRow, "id" | "name">[];
  now?: Date;
}): string {
  const agentName = new Map(input.agents.map((a) => [a.id, a.name]));
  const brandName = new Map(input.brands.map((b) => [b.id, b.name]));
  const now = input.now ?? new Date();
  const lines: string[] = [
    "# Active Command Board",
    "",
    `> Rendered from the BRIGHT OS database at ${now.toISOString()} — do not edit by hand;`,
    "> edits belong in the task notes or the HUD. This file is overwritten on every sync.",
    "",
  ];
  for (const col of BOARD_COLUMNS) {
    const rows = input.tasks.filter((t) => t.status === col.status);
    lines.push(`## ${col.label} (${rows.length})`, "");
    for (const t of rows) {
      const bits = [
        `**${t.title.replace(/\n/g, " ")}**`,
        t.agent_id ? agentName.get(t.agent_id) : null,
        t.brand_id ? brandName.get(t.brand_id) : null,
        t.due_at ? `due ${String(t.due_at).slice(0, 10)}` : null,
        t.obsidian_path ? `[[${t.obsidian_path.replace(/\.md$/, "")}]]` : null,
      ].filter(Boolean);
      lines.push(`- ${bits.join(" · ")}`);
    }
    if (rows.length === 0) lines.push("- _empty_");
    lines.push("");
  }
  return lines.join("\n");
}

export async function writeCommandBoard(md: string): Promise<string | null> {
  if (!vaultConfigured()) return null;
  return writeVaultFile(env.obsidianBoardNote, md);
}
